# Generated by Django 6.0.7 on 2026-07-21 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_last_login_date_userprofile_streak_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='issue_date',
            new_name='issued_date',
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='earned_at',
            new_name='unlocked_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='🏆', max_length=50),
        ),
        migrations.AlterField(
            model_name='badge',
            name='points_threshold',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(default='/dashboard/', max_length=255),
        ),
        migrations.AlterField(
            model_name='skilloffer',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='https://api.dicebear.com/7.x/bottts/svg?seed=learnhub', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateField(auto_now_add=True, default='2026-07-21'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
