# Generated by Django 6.0.7 on 2026-07-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_study',
            field=models.CharField(blank=True, default='Specializing in Python Full Stack & Databases', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(blank=True, default='B.Tech Computer Science', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_expertise',
            field=models.CharField(blank=True, default='Python, Django, MySQL, SQL, React JS', max_length=255),
        ),
    ]
