# Generated by Django 6.0.7 on 2026-07-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_mode',
            field=models.CharField(choices=[('Roadmap', '🗺️ Career & Skill Roadmap Guidance'), ('MockInterview', '⚡ Mock Technical Interview Practice'), ('CodeAudit', '🔍 Pair Programming & Deep Code Audit')], default='Roadmap', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mentor_name',
            field=models.CharField(default='Senior Python Architect', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
    ]
